name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Get build timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date -u '+%Y-%m-%d_%I:%M:%S%p')"
      - name: Build
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags "-X github.com/sinhashubham95/go-actuator/core.BuildStamp=${{ steps.timestamp.outputs.timestamp }} -X github.com/sinhashubham95/go-actuator/core.GitCommitID=${{ github.sha }} -X github.com/sinhashubham95/go-actuator/core.GitPrimaryBranch=${{ github.ref }} -X github.com/sinhashubham95/go-actuator/core.GitURL=https://github.com/${{ github.repository }} -X github.com/sinhashubham95/go-actuator/core.Username=${{ github.actor }} -X github.com/sinhashubham95/go-actuator/core.HostName=${{ job.container.id }}  -X github.com/sinhashubham95/go-actuator/core.GitCommitTime=${{ steps.timestamp.outputs.timestamp }} -X github.com/sinhashubham95/go-actuator/core.GitCommitAuthor=${{ github.actor }}" -o
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: moxy-${{ matrix.os }}-${{ matrix.arch }}
          path: moxy-${{ matrix.os }}-${{ matrix.arch }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download
        uses: actions/download-artifact@v2
      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
      - name: Upload
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ steps.release.outputs.id }}
          args: 'moxy-*'