name: Release

on:
  push:
    branches: [master]
    paths:
      - "version.json"

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ linux, darwin ]
        arch: [ amd64, arm64 ]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Get build timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date -u '+%Y-%m-%d_%I:%M:%S%p')"
      - name: Build
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags "-X github.com/sinhashubham95/go-actuator/core.BuildStamp=${{ steps.timestamp.outputs.timestamp }} -X github.com/sinhashubham95/go-actuator/core.GitCommitID=${{ github.sha }} -X github.com/sinhashubham95/go-actuator/core.GitPrimaryBranch=${{ github.ref }} -X github.com/sinhashubham95/go-actuator/core.GitURL=https://github.com/${{ github.repository }} -X github.com/sinhashubham95/go-actuator/core.Username=${{ github.actor }} -X github.com/sinhashubham95/go-actuator/core.HostName=${{ job.container.id }}  -X github.com/sinhashubham95/go-actuator/core.GitCommitTime=${{ steps.timestamp.outputs.timestamp }} -X github.com/sinhashubham95/go-actuator/core.GitCommitAuthor=${{ github.actor }}" -o moxy-${{ matrix.os }}-${{ matrix.arch }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: moxy-${{ matrix.os }}-${{ matrix.arch }}
          path: moxy-${{ matrix.os }}-${{ matrix.arch }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Get Current Version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "version.json"
          prop_path: "version"
      - name: Download
        uses: actions/download-artifact@v2
      - name: Tag
        id: tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: "v${{ steps.version.outputs.prop }}"
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: ${{ steps.tag.outputs.new_tag }}
          automatic_release_tag: ${{ steps.tag.outputs.new_tag }}
          files: |
            moxy-*